In [1]:
print("Hello World")

Hello World


原代码只是变量名拼错了。。。。

In [3]:
# Care with, e.g. 
long_variable_name = 1

# spot the typo?
if (True):
    long_variable_name = long_variable_name + 1
    
print(long_variable_name)

2


In [4]:
lista = [3, "a", 3.14, False]
dictb = {"key1" : 1, "key2" : 2}
tuplec = (1,2,3)

In [9]:
print(lista[0])
print(dictb["key1"])
print(dictb["key2"])
print(tuplec[2])
lista[2:3]

3
1
2
3


[3.14]

In [14]:
import random

print(random.random())
print(random.choice(["yes", "no", "maybe"]))


0.0749885840666209
yes


In [18]:
def my_median(years):
    ages = 2026 - years

    return ages
    
    
years = [1989, 1955, 2011, 1943, 1975]

In [19]:
my_median(years[0])

37

Numpy

In [20]:
import numpy as np

In [24]:
a = np.array( [-1, 0, 1] )
b = np.array( a )
print(a)
print(b)
type(b)

[-1  0  1]
[-1  0  1]


numpy.ndarray

In [27]:

a = np.arange( -2, 6, 2 )
print(a)
print(type(a))
a = np.array( [-1, 0, 1] )
b = np.array( a )
print(a)


[-2  0  2  4]
<class 'numpy.ndarray'>
[-1  0  1]


In [32]:
a = np.arange( -2, 5, 1 )
print(a)
a = np.linspace(-10, 10, 5) 
print(a)

[-2 -1  0  1  2  3  4]
[-10.  -5.   0.   5.  10.]
